// JWT token generator adapter tests.
//
// Intent: verify the JwtAdapter's HS256 access/refresh token issuance and refresh token parsing
// in isolation.
// Objective: cover access and refresh token generation, a successful parse round-trip, and the
// parse failure paths (malformed token, invalid signature, expired token).
package database_test

import (
	"os"
	"testing"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/jeffersonbrasilino/hex-api-go/internal/user/infrastructure/database"
)

func init() {
	os.Setenv("JWT_SECRET", "test-jwt-secret")
}

func TestNewJwtAdapter(t *testing.T) {
	t.Run("should return a non-nil JwtAdapter", func(t *testing.T) {
		t.Parallel()
		adapter := database.NewJwtAdapter()
		if adapter == nil {
			t.Fatal("NewJwtAdapter should return a non-nil adapter")
		}
	})
}

func TestJwtAdapter_GenerateAccessToken(t *testing.T) {
	t.Run("should return a non-empty signed token", func(t *testing.T) {
		t.Parallel()
		adapter := database.NewJwtAdapter()

		token, err := adapter.GenerateAccessToken("user-uuid", []string{"admin"})

		if err != nil {
			t.Fatalf("GenerateAccessToken should not return an error, got: %v", err)
		}
		if token == "" {
			t.Fatal("GenerateAccessToken should return a non-empty token")
		}
	})

	t.Run("should embed the user id and groups as claims", func(t *testing.T) {
		t.Parallel()
		adapter := database.NewJwtAdapter()

		token, err := adapter.GenerateAccessToken("user-uuid", []string{"admin", "operator"})
		if err != nil {
			t.Fatalf("GenerateAccessToken should not return an error, got: %v", err)
		}

		claims := jwt.MapClaims{}
		parsed, err := jwt.ParseWithClaims(token, claims, func(tok *jwt.Token) (any, error) {
			return []byte("test-jwt-secret"), nil
		})
		if err != nil || !parsed.Valid {
			t.Fatalf("access token should be parseable with the configured secret, got err: %v", err)
		}
		if claims["sub"] != "user-uuid" {
			t.Fatalf("access token should carry sub=user-uuid, got: %v", claims["sub"])
		}
		groups, ok := claims["groups"].([]any)
		if !ok || len(groups) != 2 || groups[0] != "admin" || groups[1] != "operator" {
			t.Fatalf("access token should carry the groups claim, got: %v", claims["groups"])
		}
	})
}

func TestJwtAdapter_GenerateRefreshToken(t *testing.T) {
	t.Run("should return a non-empty signed token", func(t *testing.T) {
		t.Parallel()
		adapter := database.NewJwtAdapter()

		token, err := adapter.GenerateRefreshToken("session-id")

		if err != nil {
			t.Fatalf("GenerateRefreshToken should not return an error, got: %v", err)
		}
		if token == "" {
			t.Fatal("GenerateRefreshToken should return a non-empty token")
		}
	})

	t.Run("should embed the session id as the jti claim", func(t *testing.T) {
		t.Parallel()
		adapter := database.NewJwtAdapter()

		token, err := adapter.GenerateRefreshToken("session-id")
		if err != nil {
			t.Fatalf("GenerateRefreshToken should not return an error, got: %v", err)
		}

		claims := jwt.MapClaims{}
		parsed, err := jwt.ParseWithClaims(token, claims, func(tok *jwt.Token) (any, error) {
			return []byte("test-jwt-secret"), nil
		})
		if err != nil || !parsed.Valid {
			t.Fatalf("refresh token should be parseable with the configured secret, got err: %v", err)
		}
		if claims["jti"] != "session-id" {
			t.Fatalf("refresh token should carry jti=session-id, got: %v", claims["jti"])
		}
	})
}

func TestJwtAdapter_ParseRefreshToken(t *testing.T) {
	t.Run("should recover the session id from a token generated by GenerateRefreshToken", func(t *testing.T) {
		t.Parallel()
		adapter := database.NewJwtAdapter()
		token, err := adapter.GenerateRefreshToken("session-id")
		if err != nil {
			t.Fatalf("GenerateRefreshToken should not return an error, got: %v", err)
		}

		sessionId, err := adapter.ParseRefreshToken(token)

		if err != nil {
			t.Fatalf("ParseRefreshToken should not return an error, got: %v", err)
		}
		if sessionId != "session-id" {
			t.Fatalf("ParseRefreshToken should return %q, got: %q", "session-id", sessionId)
		}
	})

	t.Run("should return an error for a malformed token", func(t *testing.T) {
		t.Parallel()
		adapter := database.NewJwtAdapter()

		sessionId, err := adapter.ParseRefreshToken("not-a-valid-jwt-token")

		if err == nil {
			t.Fatal("ParseRefreshToken should return an error for a malformed token")
		}
		if sessionId != "" {
			t.Fatalf("ParseRefreshToken should return an empty session id on error, got: %q", sessionId)
		}
	})

	t.Run("should return an error for a token signed with a different secret", func(t *testing.T) {
		t.Parallel()
		adapter := database.NewJwtAdapter()
		claims := jwt.RegisteredClaims{
			ID:        "session-id",
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(time.Hour)),
		}
		token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
		signed, err := token.SignedString([]byte("a-different-secret"))
		if err != nil {
			t.Fatalf("failed to sign test token: %v", err)
		}

		sessionId, err := adapter.ParseRefreshToken(signed)

		if err == nil {
			t.Fatal("ParseRefreshToken should return an error for a token with an invalid signature")
		}
		if sessionId != "" {
			t.Fatalf("ParseRefreshToken should return an empty session id on error, got: %q", sessionId)
		}
	})

	t.Run("should return an error for an expired token", func(t *testing.T) {
		t.Parallel()
		adapter := database.NewJwtAdapter()
		claims := jwt.RegisteredClaims{
			ID:        "session-id",
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(-time.Hour)),
		}
		token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
		signed, err := token.SignedString([]byte("test-jwt-secret"))
		if err != nil {
			t.Fatalf("failed to sign test token: %v", err)
		}

		sessionId, err := adapter.ParseRefreshToken(signed)

		if err == nil {
			t.Fatal("ParseRefreshToken should return an error for an expired token")
		}
		if sessionId != "" {
			t.Fatalf("ParseRefreshToken should return an empty session id on error, got: %q", sessionId)
		}
	})
}
