#!/usr/bin/env node
'use strict';

// Appends a new entry to the "Registro de Decisões" section of NOTES.md.
// Reads the decision text from stdin. Never overwrites prior content.
//
// Exit codes:
//   0 — entry appended successfully (stdout: confirmation + entry written)
//   1 — logical error: file not found, required section missing (stderr: detail + action)
//   2 — usage or runtime error (stderr: what failed + usage hint)

const fs       = require('fs');
const readline = require('readline');

const HELP = `
Usage: echo "<decision>" | node scripts/merge-notes.cjs <path/to/NOTES.md>

Appends a dated entry to the append-only "Registro de Decisões" section
and updates the "Última atualização" header. Idempotent per decision text.

Arguments:
  NOTES.md path   Path to the NOTES.md file (must already exist)

Stdin:
  The decision text to append (single line or short paragraph)

Exit codes:
  0   Entry appended successfully
  1   File not found or required section missing
  2   Usage or runtime error

Examples:
  echo "PRD aprovado — escopo cobre autenticação básica." | node scripts/merge-notes.cjs docs/auth/login/NOTES.md
`.trim();

if (process.argv.includes('--help') || process.argv.includes('-h')) {
  process.stdout.write(HELP + '\n');
  process.exit(0);
}

const [,, notesPath] = process.argv;

if (!notesPath) {
  process.stderr.write([
    'Error: <path/to/NOTES.md> is required.',
    'Expected: path to an existing NOTES.md file created by scaffold.cjs.',
    'Usage: echo "<decision>" | node scripts/merge-notes.cjs <path/to/NOTES.md>',
  ].join('\n') + '\n');
  process.exit(2);
}

if (!fs.existsSync(notesPath)) {
  process.stderr.write([
    `Error: file not found: "${notesPath}"`,
    `Expected: an existing NOTES.md created by scaffold.cjs.`,
    `Action: run scaffold.cjs first to initialise the file, or check the path.`,
  ].join('\n') + '\n');
  process.exit(1);
}

async function main() {
  const lines = [];
  const rl = readline.createInterface({ input: process.stdin, crlfDelay: Infinity });
  for await (const line of rl) lines.push(line);
  const newDecision = lines.join('\n').trim();

  if (!newDecision) {
    process.stderr.write([
      'Error: no decision text received via stdin.',
      'Expected: a non-empty string describing the decision and its rationale.',
      'Usage: echo "<decision>" | node scripts/merge-notes.cjs <path/to/NOTES.md>',
    ].join('\n') + '\n');
    process.exit(2);
  }

  let content = fs.readFileSync(notesPath, 'utf8');
  const today = new Date().toISOString().slice(0, 10);
  const entry = `- [${today}] ${newDecision}`;

  const SECTION = '## Registro de Decisões (append-only)';
  const idx = content.indexOf(SECTION);
  if (idx === -1) {
    process.stderr.write([
      `Error: section "${SECTION}" not found in "${notesPath}".`,
      `Expected: NOTES.md generated by scaffold.cjs from notes-template.md.`,
      `Action: verify the file was created by scaffold.cjs and was not manually edited to remove that section.`,
    ].join('\n') + '\n');
    process.exit(1);
  }

  const insertAt = idx + SECTION.length;
  content = content.slice(0, insertAt) + '\n' + entry + content.slice(insertAt);
  content = content.replace(
    /Última atualização: \d{4}-\d{2}-\d{2}/,
    `Última atualização: ${today}`
  );

  fs.writeFileSync(notesPath, content, 'utf8');
  process.stdout.write(`MERGED: ${notesPath}\n`);
  process.stdout.write(`DATA: ${today}\n`);
  process.stdout.write(`ENTRADA: ${entry}\n`);
  process.exit(0);
}

main().catch(err => {
  process.stderr.write([
    `Error: unexpected runtime failure.`,
    `Detail: ${err.message}`,
  ].join('\n') + '\n');
  process.exit(2);
});
